version: '3.8'

services:
    postgres:
        container_name: 'beadando-postgres'
        image: postgres:latest
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: beadando
            POSTGRES_HOST: postgres
        ports:
            - 5432:5432
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d:Z
        networks:
         - beadando-network
         
    keycloak:
        container_name: keycloak
        build:
          context: .
          args:
            KEYCLOAK_VERSION: 22.0.0
        command: ['start', '--optimized']
        depends_on:
          - "postgres"
        environment:
          JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
          KC_DB_URL: jdbc:postgresql://postgres/beadando
          KC_DB_USERNAME: admin
          KC_DB_PASSWORD: admin
          KC_HEALTH_ENABLED: 'true'
          KC_HTTP_ENABLED: 'true'
          KC_METRICS_ENABLED: 'true'
          KC_HOSTNAME_URL: http://localhost:8180
          KC_PROXY: reencrypt
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - "8180:8080"
          - "8787:8787"
        networks:
          - beadando-network

networks:
    beadando-network:
        name: 'beadando-network'
        driver: bridge
