CREATE ROLE beadando WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	PASSWORD '12345678';

CREATE TABLE file_info (
id serial PRIMARY KEY,
userid VARCHAR(200) NOT NULL,
filename VARCHAR(100) NOT NULL,
date_added timestamp NOT NULL
);

ALTER TABLE file_info
    ADD CONSTRAINT fk_orders_customers FOREIGN KEY (userid) REFERENCES user_entity (id);