spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/realms/beadando'

beadando:
  keycloak:
    realm: 'beadando'
    serverURL: 'http://localhost:8180'
    clientID: 'beadandobackend'
    clientSecret: 'caLCRW31Nyuwdiwkr8NCYSVLfQft1SCl'


