spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/beadando?schema=public
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/realms/beadando'
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

beadando:
  keycloak:
    realm: 'beadando'
    serverURL: 'http://localhost:8180'
    clientID: 'beadandobackend'
    clientSecret: 'caLCRW31Nyuwdiwkr8NCYSVLfQft1SCl'
  filemanager:
    rootpath: 'uploads'



